host1: 127.0.0.1
host2: 192.168.42.102
# dubbo配置
dubbo:
  protocol:
    name: dubbo # 协议名称
    port: 7090 # dubbo服务暴露的端口
  application:
    name: ${spring.application.name}
  registry:
    address: zookeeper://${host2}:2181
spring:
  application:
    name: dajiuye-order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dajiuye?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: weiwenping
  redis:
    host: ${host2}
    port: 6379
  rabbitmq:
    host: ${host2}
    virtual-host: /
    port: 5672
    # 生产端确认回调
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    username: itcast
    password: 123
    listener:
      simple:
        acknowledge-mode: manual # 开启手动确认模式
server:
  port: 8090