#Dubbo配置
dubbo:
  registry:
    address: zookeeper://${host2}:2181
  protocol:
    name: dubbo
    port: 7020

spring:
  #MySQL配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${host2}:3406/dajiuye?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

  # rabbitmq配置
  rabbitmq:
    host: ${host2}
    virtual-host: /
    port: 5672
    # 生产端确认回调
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    username: itcast
    password: 123
    listener:
      simple:
        acknowledge-mode: manual # 开启手动确认模式
  kafka:
    bootstrap-servers: ${host2}:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
# aliyun oss
# 地域节点
aliyun.endPoint: oss-cn-shenzhen.aliyuncs.com
# Bucket 域名
aliyun.urlPrefix: https://dajiuye2.oss-cn-shenzhen.aliyuncs.com/
# accessKey Id
aliyun.accessKeyId: LTAI5tP7Kk3xA1M4oJawzdH7
# accessKey Secret
aliyun.accessKeySecret: rTlHPzyvVTfretbT4jPKRNaLgauMzu
# 你的Bucket名称
aliyun.bucketName: dajiuye2
# 目标文件夹
aliyun.fileHost: test

# 微信小程序的appid和secret
wx:
  url: api.weixin.qq.com/sns/jscode2session
  appid: wxffd8f31f5bb7f05f
  secret: baa7959cdd43af09c9c5bcb0d3e426ea
  grant_type: authorization_code

# 发送微信http请求的
httppool:
  max_total: 200
  max_per_route: 100
  connect_timeout: 5000
  connection_request_timeout: 1000
  socket_timeout: 65000
  validate_after_inactivity: 2000
