# dubbo服务配置
dubbo:
  registry:
    address: zookeeper://${host2}:2181
  protocol:
    port: 7060
    name: dubbo
spring:
  #MySQL配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${host1}:3306/dajiuye?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: weiwenping