# dubbo配置
dubbo:
  registry:
    address: zookeeper://192.168.42.101:2181
spring:
  # MySQL配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dajiuye?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: weiwenping

  # rabbitmq 配置
  rabbitmq:
    host: 192.168.42.100
    virtual-host: /
    port: 5672
    # 生产端确认回调
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    username: itcast
    password: 123
    listener:
      simple:
        acknowledge-mode: manual # 开启手动确认模式

# aliyun oss
# 地域节点
aliyun.endPoint: oss-cn-shenzhen.aliyuncs.com
# Bucket 域名
aliyun.urlPrefix: https://dajiuye2.oss-cn-shenzhen.aliyuncs.com/
# accessKey Id
aliyun.accessKeyId: LTAI5tP7Kk3xA1M4oJawzdH7
# accessKey Secret
aliyun.accessKeySecret: rTlHPzyvVTfretbT4jPKRNaLgauMzu
# 你的Bucket名称
aliyun.bucketName: dajiuye2
# 目标文件夹
aliyun.fileHost: test

# 微信小程序appid和secret配置
wx:
  url: api.weixin.qq.com/sns/jscode2session
  appid: wxffd8f31f5bb7f05f
  secret: baa7959cdd43af09c9c5bcb0d3e426ea
  grant_type: authorization_code

# 发送微信http请求的
httppool:
  max_total: 200
  max_per_route: 100
  connect_timeout: 5000
  connection_request_timeout: 1000
  socket_timeout: 65000
  validate_after_inactivity: 2000